/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  carouselItems,
} from './components/wc-materializecss-carousel/wc-materializecss-carousel';

export namespace Components {
  interface WcMaterializecssCarousel {
    'items': carouselItems[];
    'template': boolean;
  }
}

declare global {


  interface HTMLWcMaterializecssCarouselElement extends Components.WcMaterializecssCarousel, HTMLStencilElement {}
  var HTMLWcMaterializecssCarouselElement: {
    prototype: HTMLWcMaterializecssCarouselElement;
    new (): HTMLWcMaterializecssCarouselElement;
  };
  interface HTMLElementTagNameMap {
    'wc-materializecss-carousel': HTMLWcMaterializecssCarouselElement;
  }
}

declare namespace LocalJSX {
  interface WcMaterializecssCarousel extends JSXBase.HTMLAttributes<HTMLWcMaterializecssCarouselElement> {
    'items'?: carouselItems[];
    'onMcssCarouselComponentDidLoad'?: (event: CustomEvent<any>) => void;
    'template'?: boolean;
  }

  interface IntrinsicElements {
    'wc-materializecss-carousel': WcMaterializecssCarousel;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


